### ISSUE TITLE
Work todo

### ISSUE THREAD

**Issue by joesepi** [sometotal/takedownnotice.rocks#1]
- [x] add id to episode frontmatter (1-7)
- [x] change title to episode title
- [x] delete episode content
- [x] add link to each episode
- [x] rename files to 00x.md
- [ ] use episode id for url slug
- [x] show link in episode blurbs on homepage and in episode content page
- [x] format episode titles using id + title (Ep 1 - Inaugural)
- [ ] design fists logo
